# Generated by Django 5.1.7 on 2025-03-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='irisdb',
            name='petal_length',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
